
name: Check Lua Formatting
run-name: ${{ github.actor }}
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  stylua-check:
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}

      - name: Install Stylua
        run: |
          curl -L -o stylua.zip https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux.zip
          unzip stylua.zip -d /usr/local/bin
          chmod +x /usr/local/bin/stylua

      - name: Run Stylua Check
        id: stylua_check
        run: |
          /usr/local/bin/stylua --check .
        continue-on-error: true

      - name: Display Stylua Output
        if: failure()
        run: |
          echo "Stylua found issues. Please fix them."
          echo "Running Stylua to show issues:"
          /usr/local/bin/stylua --check .

