# Check Lua Formatting
name: Check Lua Formatting
run-name: ${{ github.actor }}
on: 
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master

jobs:
  stylua-check:
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         version: latest 
          args: --check .
